# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiwQ3Cvnr_3Ee2vbUfW-x9ulKyCT_B6N
"""

# Install the streamlit library if it's not already installed


# Now you can import and use streamlit
import streamlit as st
import pandas as pd

st.title("Job Listing Clusters")

# Assuming 'clustered_jobs.csv' is in the same directory as your notebook
df = pd.read_csv('clustered_jobs.csv')
clusters = df['Cluster'].unique()

cluster_selected = st.sidebar.multiselect("Select clusters", clusters)

if cluster_selected:
    filtered = df[df['Cluster'].isin(cluster_selected)]
    st.write(filtered)
else:
    st.write(df)
