# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVI-x266CWP2RiuDnair5L1tSR9KHKLC
"""

# Ensure streamlit is installed
!pip install streamlit

import streamlit as st
import pandas as pd

st.title("Job Listing Clusters")

# Ensure 'clustered_jobs.csv' is in the same directory as this notebook
# or provide the correct path to the file.
try:
    df = pd.read_csv('/content/clustered_jobs (2).csv')
except FileNotFoundError:
    st.error("Error: 'clustered_jobs.csv' not found. Please make sure the file is in the correct directory.")
    # Optionally, you could stop the Streamlit app execution here
    st.stop()

clusters = df['Cluster'].unique()

cluster_selected = st.sidebar.multiselect("Select clusters", clusters)

if cluster_selected:
    filtered = df[df['Cluster'].isin(cluster_selected)]
    st.write(filtered)
else:
    st.write(df)